version: "3"

services:
  app:
    build: app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    build: database
    ports:
      - "6379:6379"
    volumes:
      - .data:/data