version: "3.8"

services:
  app:
    build: app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: redis:alpine3.16
    hostname: redis
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf: